server:
  port: 9000
spring:
  application:
    name: dubbo-springboot-consumer
  dubbo:
    application:
      name: dubbo-springboot-consumer
    registry:
      address: zookeeper://192.168.137.95:2181
