spring:
  application:
    name: dubbo-springboot-consumer
  dubbo:
    application:
      name: dubbo-consumer-1
      owner: testuser
    protocol:
      name: dubbo
    registry: zookeeper://localhost:2181
    base-package: com.abc.dubbo.consumerdemo.controller
    consumer:
      timeout: 1000 
      check: true
server:
  port: 9091