server:
  port: 9001
spring:
  application:
    name: dubbo-springboot-provider
  dubbo:
    application:
      name: dubbo-springboot-provider
    registry:
      address: zookeeper://192.168.137.95:2181
    protocol:
      dubbo:
        port: 20800
      rest:
        port: 20801