spring:
  application:
    name: dubbo-springboot-provider
  dubbo:
    application:
      name: dubbo-provider-1
    protocol:
      name: dubbo
      port: 20800 
    server: true
    registry: zookeeper://localhost:2181
server:
  port: 9090
